const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');

const { createKnownPrettyPageSlugToFile } = require('../../server/config/page-routing');

test('agenda app page is available as pretty page and uses shared agenda endpoints', () => {
  const pagePath = path.join(__dirname, '../../agendaapp.html');
  const pageSource = fs.readFileSync(pagePath, 'utf8');
  const prettyPages = createKnownPrettyPageSlugToFile(new Set(['agendaapp.html']));

  assert.equal(prettyPages.get('agendaapp'), 'agendaapp.html');
  assert.match(pageSource, /<title>Softora Agenda App<\/title>/);
  assert.match(pageSource, /apple-mobile-web-app-capable/);
  assert.match(pageSource, /Softora Agenda App/);
  assert.match(pageSource, /id="agendaAppAppointments"/);
  assert.match(pageSource, /id="agendaAppForm"/);
  assert.match(pageSource, /data|zelfde agenda-data/i);
  assert.match(pageSource, /\/api\/agenda\/appointments\?limit=250&fresh=1/);
  assert.match(pageSource, /\/api\/agenda\/appointments\/manual/);
  assert.match(pageSource, /id="type-overlay"/);
  assert.match(pageSource, /Kies afspraak type/);
  assert.match(pageSource, /data-type="private">Privé/);
  assert.match(pageSource, /data-type="business">Zakelijk/);
  assert.match(pageSource, /openTypeChoice\(day\)/);
  assert.match(pageSource, /id="meeting-overlay"/);
  assert.match(pageSource, /Welke meeting\?/);
  assert.match(pageSource, /data-meeting-type="website">Website/);
  assert.match(pageSource, /data-meeting-type="business">Bedrijfssoftware/);
  assert.match(pageSource, /data-meeting-type="voice">Voicesoftware/);
  assert.match(pageSource, /data-meeting-type="chatbot">Chatbot/);
  assert.match(pageSource, /id="meeting-back"/);
  assert.match(pageSource, /id="meeting-next"/);
  assert.match(pageSource, /id="agendaAppWho"/);
  assert.match(pageSource, /<option value="serve">Servé<\/option>/);
  assert.match(pageSource, /<option value="martijn">Martijn<\/option>/);
  assert.match(pageSource, /<option value="both">Allebei<\/option>/);
  assert.match(pageSource, /actor: 'agendaapp'/);
  assert.match(pageSource, /legendChoice:appointmentType==='business'\?businessMeetingType:'manual-overig'/);
  assert.match(pageSource, /businessMeetingType='website'/);
  assert.match(pageSource, /who:'serve'/);
  assert.match(pageSource, /renderMobileAgendaApp/);
  assert.match(pageSource, /--purple:#8B2252/);
  assert.match(pageSource, /body\{font-family:'Inter',sans-serif;/);
  assert.match(pageSource, /\.topbar-week\{font-family:'Oswald',sans-serif;/);
  assert.doesNotMatch(pageSource, /DM Sans|DM Serif Display/);
  assert.doesNotMatch(pageSource, /id="clock"/);
  assert.doesNotMatch(pageSource, /topbar-time/);
  assert.doesNotMatch(pageSource, /<footer class="footer">/);
  assert.doesNotMatch(pageSource, /tab-btn/);
  assert.doesNotMatch(pageSource, /id="btn-today"/);
  assert.doesNotMatch(pageSource, /topbar-today/);
  assert.doesNotMatch(pageSource, /id="btn-refresh"/);
  assert.doesNotMatch(pageSource, /aria-label="Ververs agenda"/);
  assert.doesNotMatch(pageSource, /aria-label="Instellingen"/);
  assert.doesNotMatch(pageSource, /topbar-icons/);
  assert.doesNotMatch(pageSource, /icon-btn/);
  assert.doesNotMatch(pageSource, /id="dots"/);
  assert.doesNotMatch(pageSource, /updateDots/);
  assert.doesNotMatch(pageSource, /agendaAppSyncStatus/);
  assert.doesNotMatch(pageSource, /sync-status/);
  assert.doesNotMatch(pageSource, /Offline/);
  assert.doesNotMatch(pageSource, /Live sync/);
  assert.doesNotMatch(pageSource, /Beschikbaarheid/);
  assert.doesNotMatch(pageSource, /Delen/);
  assert.doesNotMatch(pageSource, /color-dot/);
  assert.match(pageSource, /\.day-cell\.is-today\{background:var\(--purple-light\);box-shadow:inset 0 0 0 1\.5px var\(--purple-dim\)\}/);
  assert.match(pageSource, /Hele dag/);
  assert.match(pageSource, /Week/);
});
