const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const repoRoot = path.resolve(__dirname, '../..');
const endGameCardFiles = [
  '2030.png', 'bestaanszekerheid-bedrijf.png', 'black-gel-voorraad.png', 'bodyfat-onder-13.png',
  'eigen-automaat-rijden.png', 'eigen-cinema.png', 'eigen-kantoor.png', 'eigen-koophuis-kopen.png',
  'gewenst-lang-kapsel.png', 'gewenste-kledingkast.png', 'gezichtsbeharing-naar-wens.png',
  'gezondheidscenter.png', 'haartransplantatie.png', 'kantoorpand-in-haaren.png',
  'ketting-armband.png', 'leuke-vriendin.png', 'nieuwe-whoop.png', 'oktober-2024.png',
  'prp-behandeling.png',
  'ruben-zet-toto.png', 'rubens-company.png', 'rubens-trading-system.png',
  'serves-gezondheidsdossier.png', 'tanden-rechtzetten.png', 'tandenbleek-voorraad.png',
  'transfermarkt.png', 'vijf-kilo-spiermassa.png', 'world-watcher.png'
];

function read(fileName) {
  return fs.readFileSync(path.join(repoRoot, fileName), 'utf8');
}

test('live momentum page renders the requested dashboard surface', () => {
  const html = read('live-momentum.html');

  assert.match(html, /<title>ATTACK, ATTACK, ATTACK\. \| Softora<\/title>/);
  assert.match(html, /href="\/assets\/fonts\.css\?v=20260409a"/);
  assert.match(html, /href="\/assets\/personnel-theme\.css\?v=20260519b"/);
  assert.match(html, /href="\/assets\/premium-sidebar-autopilot\.css\?v=20260611a"/);
  assert.match(html, /href="\/assets\/live-momentum\.css\?v=20260717e"/);
  assert.match(html, /href="\/assets\/live-momentum-video\.css\?v=20260717b"/);
  assert.match(html, /<script src="\/assets\/personnel-theme\.js\?v=20260715a" defer><\/script>/);
  assert.match(html, /<script src="\/assets\/premium-sidebar-autopilot\.js\?v=20260611a" defer><\/script>/);
  assert.match(html, /<script src="\/assets\/premium-ui-state-client\.js\?v=20260605a"><\/script>/);
  assert.match(html, /<script src="\/assets\/live-momentum-icon-catalog\.js\?v=20260716b" defer><\/script>/);
  assert.match(html, /<script src="\/assets\/live-momentum-goal-actions\.js\?v=20260716a" defer><\/script>/);
  assert.match(html, /<script src="\/assets\/live-momentum-endgame-interactions\.js\?v=20260717c" defer><\/script>/);
  assert.match(html, /<script src="\/assets\/live-momentum-endgame-cards\.js\?v=20260717c" defer><\/script>/);
  assert.match(html, /<script src="\/assets\/live-momentum-video\.js\?v=20260717b" defer><\/script>/);
  assert.match(html, /<script src="\/assets\/live-momentum-calendar\.js\?v=20260717a" defer><\/script>/);
  assert.match(html, /<script src="\/assets\/live-momentum\.js\?v=20260717b" defer><\/script>/);
  assert.match(html, /<div class="dashboard-layout momentum-layout" data-sidebar-shell="canonical">/);
  assert.match(html, /<aside class="sidebar" data-sidebar-ready="true" data-static-sidebar="1" aria-label="Premium navigatie">/);
  assert.match(html, /data-sidebar-key="dashboard"/);
  assert.match(html, /data-sidebar-key="settings"/);
  assert.match(html, /assets\/premium-sidebar-profile-prefill\.js\?v=20260715a/);
  assert.doesNotMatch(html, /data-live-momentum-sidebar-host/);
  assert.match(html, /<main class="main-content momentum-page" aria-labelledby="momentum-title">\s*<div class="momentum-art-quotes" aria-hidden="true">/);
  assert.match(html, /<h1 id="momentum-title">ATTACK, ATTACK, ATTACK\.<\/h1>/);
  assert.match(html, /<p>Back on Track\.<\/p>/);
  assert.match(html, /class="momentum-video-trigger"[^>]*aria-label="Motivatievideo openen"[^>]*aria-haspopup="dialog"/);
  assert.match(html, /<dialog class="momentum-video-dialog" id="momentum-video-dialog" aria-labelledby="momentum-video-title">/);
  assert.match(html, /<h2 id="momentum-video-title">ATTACK MODE<\/h2>/);
  assert.match(html, /class="momentum-video-stage" data-momentum-video-player/);
  assert.doesNotMatch(html, /youtube\.com\/shorts|youtu\.be/);
  assert.doesNotMatch(html, /Juli 2026 .* gestart op 13 juli/);
  assert.doesNotMatch(html, /today-score|score-label|Score vandaag/);
  assert.doesNotMatch(html, /score-points|100 \/ 100|punten<\/span>/);
  assert.match(html, /<div class="bar-chart" aria-hidden="true"><\/div>/);
  assert.doesNotMatch(html, /chart-switch|data-chart-mode|Grafiekweergave/);
  assert.match(html, /<div class="habit-grid" role="table" aria-label="Momentum taken"><\/div>/);
  assert.match(html, /live-momentum-calendar\.js\?v=/);
  assert.ok(html.indexOf('live-momentum-calendar.js') < html.indexOf('live-momentum.js'));
  assert.match(html, /<\/section>\s*<h2 class="end-game-title">HET EINDSPEL<\/h2>\s*<section class="end-game-goals"/);
  assert.match(html, /<h2 class="end-game-title">HET EINDSPEL<\/h2>\s*<section class="end-game-goals" aria-label="Het Eindspel doelen">/);
  assert.match(html, /<div class="end-game-goal-track"><\/div>/);
  assert.doesNotMatch(html, /data-end-game-goal-index|Schrijf je doel/);
  assert.deepEqual(
    fs.readdirSync(path.join(repoRoot, 'assets/live-momentum-endgame-cards')).filter((file) => file.endsWith('.png')).sort(),
    endGameCardFiles
  );
  assert.match(html, /<span class="momentum-art-quote is-end-game">The end game is to win<\/span>/);
  assert.match(html, /<span class="momentum-art-quote is-attack">Attack, attack, attack<\/span>/);
  assert.doesNotMatch(html, /Sleeping is for losers|is-sleeping/i);
  assert.doesNotMatch(html, /In life there are winners and losers|is-winners/i);
  assert.doesNotMatch(html, /Nog een rondje voor die oude dagen|is-old-days/i);
  assert.match(html, /<span class="momentum-watermark">[\s\S]*Never[\s\S]*Ever[\s\S]*Quit[\s\S]*<\/span>/);
  assert.match(html, /De huidige dag en momentumscore worden automatisch bijgewerkt/);
  assert.doesNotMatch(html, /laatste 30 dagen/);
  assert.doesNotMatch(html, /Dag<br>/);
  assert.doesNotMatch(html, /chart-legend|legend-dot|Legenda/);
  assert.doesNotMatch(html, /Groen|Oranje|Rood/);
  assert.doesNotMatch(html, /Dag 1 toevoegen/);
  assert.doesNotMatch(html, /Discipline vandaag/);
  assert.doesNotMatch(html, /Focus\. Consistentie\. Groei\./);
  assert.doesNotMatch(html, /motivation-strip/);
  assert.doesNotMatch(html, /closing-quote/);
  assert.doesNotMatch(html, /Nog te gaan/);
  assert.doesNotMatch(html, /<script(?![^>]*\bsrc=)[^>]*>/i);
});

test('live momentum stylesheet keeps the visual replica self-contained', () => {
  const css = read('assets/live-momentum.css');
  const videoCss = read('assets/live-momentum-video.css');

  assert.match(css, /--page-bg:\s*#f8f7f4;/);
  assert.match(css, /--ink:\s*#1a1a2e;/);
  assert.match(css, /--muted:\s*#606272;/);
  assert.match(css, /--muted-soft:\s*#9599a8;/);
  assert.match(css, /--font-sans:\s*"Inter"/);
  assert.match(css, /--font-display:\s*"Oswald"/);
  assert.match(css, /--good:\s*#2ecc71;/);
  assert.match(css, /--warning:\s*#f39c12;/);
  assert.match(css, /--danger:\s*#e74c3c;/);
  assert.match(css, /body\s*\{[\s\S]*background:\s*var\(--page-bg\);/);
  assert.match(css, /body\s*\{[\s\S]*font-family:\s*var\(--font-sans\);/);
  assert.match(css, /\.momentum-page\s*\{[\s\S]*position:\s*relative;[\s\S]*isolation:\s*isolate;[\s\S]*overflow:\s*hidden;/);
  assert.match(css, /\.momentum-head h1\s*\{[\s\S]*font-family:\s*var\(--font-display\);/);
  assert.match(css, /\.momentum-head h1\s*\{[\s\S]*font-size:\s*2rem;/);
  assert.match(css, /\.momentum-head h1\s*\{[\s\S]*text-transform:\s*uppercase;/);
  assert.doesNotMatch(css, /\.momentum-video-trigger|\.momentum-video-dialog|\.momentum-video-shell/);
  assert.match(videoCss, /\.momentum-video-trigger\s*\{[\s\S]*width:\s*46px;[\s\S]*height:\s*46px;[\s\S]*cursor:\s*pointer;/);
  assert.match(videoCss, /\.momentum-video-dialog::backdrop\s*\{[\s\S]*backdrop-filter:\s*blur\(12px\);/);
  assert.match(videoCss, /\.momentum-video-dialog\s*\{[\s\S]*position:\s*fixed;[\s\S]*inset:\s*0;[\s\S]*width:\s*100vw;[\s\S]*height:\s*100dvh;/);
  assert.match(videoCss, /\.momentum-video-dialog\[open\]\s*\{[\s\S]*display:\s*grid;[\s\S]*place-items:\s*center;/);
  assert.match(videoCss, /\.momentum-video-shell\s*\{[\s\S]*width:\s*min\(88vw, 430px, calc\(\(100dvh - 110px\) \* \.5625\)\);/);
  assert.match(videoCss, /\.momentum-video-stage\s*\{[\s\S]*aspect-ratio:\s*9 \/ 16;/);
  assert.match(videoCss, /body\.momentum-video-open\s*\{[\s\S]*overflow:\s*hidden;/);
  const letterSpacingValues = Array.from(css.matchAll(/letter-spacing:\s*([^;]+);/g), (match) => match[1].trim());
  assert.ok(letterSpacingValues.length > 0);
  assert.deepEqual([...new Set(letterSpacingValues)], ['0']);
  assert.doesNotMatch(css, /purple/i);
  assert.doesNotMatch(css, /88366b|74265c|91436f|7f426b/i);
  assert.match(css, /\.bar-chart\s*\{[\s\S]*grid-template-columns:\s*repeat\(var\(--day-count, 31\),/);
  assert.match(css, /\.bar-chart\s*\{[\s\S]*--average-score:\s*\.65;[\s\S]*--average-line-y:\s*57\.4px;[\s\S]*position:\s*relative;/);
  assert.match(css, /\.bar-chart::before,\s*\.bar-chart::after\s*\{[\s\S]*var\(--chart-total-height\) - var\(--chart-max-height\) - var\(--chart-axis-height\)[\s\S]*\+ var\(--average-line-y\)[\s\S]*pointer-events:\s*none;/);
  assert.match(css, /\.bar-chart::before\s*\{[\s\S]*border-top:\s*2px dotted rgba\(96, 98, 114, \.52\);/);
  assert.match(css, /\.bar-chart::after\s*\{[\s\S]*content:\s*"AVARAGE";[\s\S]*font-family:\s*var\(--font-display\);/);
  assert.match(css, /\.bar-wrap\s*\{[\s\S]*position:\s*relative;[\s\S]*z-index:\s*1;/);
  assert.match(css, /\.chart-card\s*\{[\s\S]*--chart-max-height:\s*164px;[\s\S]*--chart-axis-height:\s*26px;[\s\S]*--chart-total-height:\s*218px;/);
  assert.match(css, /\.chart-scale\s*\{[\s\S]*top:\s*calc\(1\.2rem \+ var\(--chart-total-height\) - var\(--chart-max-height\) - var\(--chart-axis-height\)\);[\s\S]*bottom:\s*calc\(1rem \+ var\(--chart-axis-height\)\);/);
  assert.match(css, /\.chart-scale span\s*\{[\s\S]*position:\s*absolute;[\s\S]*transform:\s*translateY\(-50%\);/);
  assert.match(css, /\.chart-scale span:nth-child\(1\)\s*\{\s*top:\s*0;\s*\}[\s\S]*nth-child\(2\)\s*\{\s*top:\s*25%;\s*\}[\s\S]*nth-child\(3\)\s*\{\s*top:\s*50%;\s*\}[\s\S]*nth-child\(4\)\s*\{\s*top:\s*75%;\s*\}[\s\S]*nth-child\(5\)\s*\{\s*top:\s*100%;\s*\}/);
  assert.match(css, /\.bar-wrap\s*\{[\s\S]*grid-template-rows:\s*var\(--chart-max-height\) var\(--chart-axis-height\);/);
  assert.doesNotMatch(css, /chart-switch|is-line-mode|\.line-(?:stage|grid|segment|point|day-axis)/);
  assert.match(css, /\.habit-grid\s*\{[\s\S]*width:\s*100%;[\s\S]*grid-template-columns:\s*minmax\(190px, 12vw\) repeat\(var\(--day-count, 31\), minmax\(32px, 1fr\)\);[\s\S]*min-width:\s*min\(100%, 1320px\);/);
  assert.doesNotMatch(css, /\.habit-grid\s*\{[^}]*min-width:\s*1320px;/);
  assert.match(css, /width:\s*100%;/);
  assert.doesNotMatch(css, /width:\s*min\(1320px, 100%\);/);
  assert.doesNotMatch(css, /\.momentum-hero,\s*\.habit-board,\s*\.closing-quote/);
  assert.doesNotMatch(css, /\.chart-card\s*\{[^}]*border-top:/);
  assert.doesNotMatch(css, /\.chart-card\s*\{[^}]*border-bottom:/);
  assert.match(css, /\.habit-board\s*\{[^}]*overflow-x:\s*auto;[^}]*scrollbar-width:\s*none;/);
  assert.match(css, /\.habit-board::\-webkit-scrollbar\s*\{[^}]*display:\s*none;/);
  assert.match(css, /\.end-game-title\s*\{[\s\S]*margin:\s*clamp\(3\.5rem, 7vh, 6rem\) auto 0;[\s\S]*font-family:\s*var\(--font-display\);[\s\S]*font-size:\s*2rem;[\s\S]*text-align:\s*center;/);
  assert.match(css, /\.momentum-hero,\s*\.habit-board,\s*\.end-game-title,\s*\.end-game-goals\s*\{[\s\S]*z-index:\s*1;/);
  assert.match(css, /\.end-game-goals\s*\{[\s\S]*overflow-x:\s*auto;[\s\S]*scroll-padding-inline-start:\s*3rem;[\s\S]*scroll-behavior:\s*auto;[\s\S]*scrollbar-width:\s*none;/);
  assert.match(css, /\.end-game-goals::\-webkit-scrollbar\s*\{[^}]*display:\s*none;/);
  assert.doesNotMatch(css, /scroll-snap-(?:type|align)/);
  assert.match(css, /@media \(max-width:\s*1200px\)[\s\S]*\.end-game-goals\s*\{[\s\S]*scroll-padding-inline-start:\s*18px;/);
  assert.match(css, /@media \(max-width:\s*520px\)[\s\S]*\.end-game-goals\s*\{[\s\S]*scroll-padding-inline-start:\s*12px;/);
  assert.match(css, /\.end-game-goal-track\s*\{[\s\S]*display:\s*flex;[\s\S]*width:\s*max-content;/);
  assert.match(css, /\.end-game-goal-card\s*\{[\s\S]*flex:\s*0 0 clamp\(190px, 13vw, 220px\);[\s\S]*min-height:\s*clamp\(290px, 33vh, 340px\);/);
  assert.match(css, /\.end-game-goal-card--mission\s*\{[\s\S]*overflow:\s*hidden;[\s\S]*padding:\s*0;[\s\S]*border:\s*0;/);
  assert.match(css, /\.end-game-goal-card--mission\s*\{[\s\S]*backdrop-filter:\s*none;[\s\S]*contain:\s*paint;/);
  assert.match(css, /\.end-game-goal-card--mission\s*\{[\s\S]*cursor:\s*grab;[\s\S]*touch-action:\s*pan-y;[\s\S]*user-select:\s*none;/);
  assert.match(css, /\.end-game-goals\.is-card-reordering\s*\{[\s\S]*cursor:\s*grabbing;/);
  assert.match(css, /\.end-game-goal-card--mission\.is-card-dragging\s*\{[\s\S]*will-change:\s*transform;/);
  assert.match(css, /\.end-game-goal-card--mission img\s*\{[\s\S]*width:\s*100%;[\s\S]*height:\s*100%;[\s\S]*object-fit:\s*cover;/);
  assert.match(css, /\.end-game-card-photo-image\s*\{[\s\S]*position:\s*absolute;[\s\S]*object-fit:\s*cover;/);
  assert.match(css, /\.end-game-card-name\s*\{[\s\S]*text-transform:\s*uppercase;/);
  assert.match(css, /\.end-game-card-target\s*\{[\s\S]*border-radius:\s*50%;/);
  assert.match(css, /\.end-game-mission-complete\s*\{[\s\S]*background:\s*linear-gradient\([\s\S]*opacity:\s*0;/);
  assert.match(css, /\.end-game-goal-card--mission\.is-completed \.end-game-mission-complete\s*\{[\s\S]*opacity:\s*1;[\s\S]*visibility:\s*visible;/);
  assert.match(css, /\.end-game-mission-actions\s*\{[\s\S]*position:\s*absolute;[\s\S]*z-index:\s*3;/);
  assert.match(css, /\.end-game-mission-actions\[hidden\]\s*\{[\s\S]*display:\s*none;/);
  assert.match(css, /\.momentum-art-quotes\s*\{[\s\S]*position:\s*absolute;[\s\S]*z-index:\s*0;[\s\S]*inset:\s*0;[\s\S]*pointer-events:\s*none;/);
  assert.match(css, /\.momentum-art-quote\s*\{[\s\S]*position:\s*absolute;[\s\S]*color:\s*transparent;[\s\S]*font-family:\s*var\(--font-display\);[\s\S]*\-webkit-text-stroke:\s*1px rgba\(26, 26, 46, \.07\);/);
  assert.doesNotMatch(css, /is-sleeping/);
  assert.doesNotMatch(css, /is-winners|is-old-days/);
  assert.match(css, /\.momentum-watermark\s*\{[\s\S]*pointer-events:\s*none;/);
  assert.match(css, /\.momentum-watermark\s*\{[\s\S]*\-webkit-text-stroke:\s*1px rgba\(26, 26, 46, \.075\);/);
  assert.match(css, /\.momentum-watermark span:last-child\s*\{[\s\S]*rgba\(35, 159, 88, \.045\)/);
  assert.doesNotMatch(css, /\.chart-legend|\.legend-dot/);
  assert.match(css, /\.bar\.is-warning\s*\{[\s\S]*var\(--warning\)/);
  assert.match(css, /\.bar\.is-danger\s*\{[\s\S]*var\(--danger\)/);
  assert.match(css, /\.status\.is-today-end\s*\{[\s\S]*border-bottom:\s*2px solid var\(--good-line\);/);
  assert.match(css, /\.status\.is-untracked::before\s*\{[\s\S]*background:\s*#d4d9df;/);
  assert.match(css, /\.status\.is-untracked\.is-empty::before\s*\{[\s\S]*width:\s*18px;[\s\S]*border:\s*2px solid #e1e0e5;[\s\S]*background:\s*#fff;/);
  assert.match(css, /\.status\.is-missed::before\s*\{[\s\S]*background-color:\s*var\(--danger\);/);
  assert.doesNotMatch(css, /\.status\.is-soft|is-soft::before/);
  assert.match(css, /\.habit-label:focus\s*\{[\s\S]*box-shadow:\s*0 0 0 2px rgba\(86, 196, 134, \.34\);/);
  assert.match(css, /\.add-goal\s*\{[\s\S]*border:\s*0;/);
  assert.match(css, /\.add-goal\s*\{[\s\S]*border-radius:\s*0;/);
  assert.match(css, /\.add-goal\s*\{[\s\S]*background:\s*transparent;/);
  assert.match(css, /\.add-goal\s*\{[\s\S]*position:\s*absolute;[\s\S]*left:\s*0;[\s\S]*width:\s*16px;[\s\S]*height:\s*28px;/);
  assert.match(css, /\.goal-icon-button\s*\{[\s\S]*cursor:\s*pointer;/);
  assert.match(css, /\.goal-drag-handle\s*\{[\s\S]*cursor:\s*grab;/);
  assert.match(css, /\.goal-row-actions\s*\{[\s\S]*position:\s*fixed;[\s\S]*z-index:\s*1000;/);
  assert.match(css, /\.goal-row-actions\[hidden\]\s*\{[\s\S]*display:\s*none;/);
  assert.match(css, /\.goal-remove-action\s*\{[\s\S]*color:\s*#c83e36;/);
  assert.match(css, /\.habit-name\.is-drop-target\s*\{[\s\S]*box-shadow:\s*inset 3px 0 0 var\(--good\);/);
  assert.match(css, /\.icon-picker-search\s*\{[\s\S]*width:\s*100%;/);
  assert.match(css, /\.icon-picker-results\s*\{[\s\S]*grid-template-columns:/);
  assert.match(css, /\.icon-picker-categories\s*\{[\s\S]*overflow-x:\s*auto;/);
  assert.match(css, /\.icon-picker-category\[aria-pressed="true"\]/);
  assert.match(css, /\.icon-picker-backdrop\[hidden\]\s*\{[\s\S]*display:\s*none;/);
  assert.doesNotMatch(css, /\.habit-add(?:-cell)?\s*\{/);
  assert.doesNotMatch(css, /\.score-points\s*\{/);
  assert.doesNotMatch(css, /\.today-score|\.score-label/);
  assert.doesNotMatch(css, /\.habit-name-empty/);
  assert.match(css, /\.habit-spacer\s*\{[\s\S]*font-family:\s*var\(--font-display\);/);
  assert.match(css, /\.habit-spacer\s*\{[\s\S]*font-weight:\s*500;/);
  assert.doesNotMatch(css, /\.motivation-strip/);
  assert.doesNotMatch(css, /\.quote-card/);
  assert.doesNotMatch(css, /\.closing-quote/);
  assert.match(css, /\.status:focus-visible::before\s*\{[\s\S]*box-shadow:\s*0 0 0 3px rgba\(86, 196, 134, \.3\);/);
  assert.match(css, /@media \(max-width:\s*780px\)/);
});

test('live momentum script wires habit toggles to chart and persisted state', () => {
  const js = read('assets/live-momentum.js');
  const goalActionsJs = read('assets/live-momentum-goal-actions.js');
  const endGameCardsJs = read('assets/live-momentum-endgame-cards.js');
  const endGameInteractionsJs = read('assets/live-momentum-endgame-interactions.js');
  const videoCss = read('assets/live-momentum-video.css');
  const videoJs = read('assets/live-momentum-video.js');

  assert.match(js, /window\.SoftoraMomentumCalendar/);
  assert.match(js, /calendar\.getCurrentPeriod\(\)/);
  assert.match(js, /function getCurrentPeriodDay\(date = new Date\(\)\)/);
  assert.match(js, /let TODAY = getCurrentPeriodDay\(\);/);
  assert.match(js, /window\.setInterval\(refreshToday, TODAY_REFRESH_MS\);/);
  assert.match(js, /window\.addEventListener\('focus', refreshToday\);/);
  assert.doesNotMatch(js, /today:\s*13/);
  assert.match(js, /const TOTAL_DAYS = DAYS\.length;/);
  assert.match(js, /PERIOD\.shortLabel/);
  assert.match(js, /DEFAULT_GOALS/);
  assert.match(js, /window\.SoftoraMomentumIconCatalog/);
  assert.match(js, /ICON_CATEGORIES/);
  assert.match(js, /function renderIconPickerCategories\(\)/);
  assert.match(js, /Zoek op icoon of betekenis/);
  assert.match(js, /Workout/);
  assert.match(js, /90 min deep work/);
  assert.match(js, /Dagdoel behalen/);
  assert.match(js, /Gezonde voeding/);
  assert.match(js, /function getScoreBand\(score\)/);
  assert.match(js, /function getChartMaxHeight\(wrap\)[\s\S]*getComputedStyle\(wrap\)[\s\S]*--chart-max-height/);
  assert.doesNotMatch(js, /const CHART_MAX_HEIGHT/);
  assert.match(js, /function toggleCell\(cell\)/);
  assert.match(js, /if \(isChecked\(cell\)\)\s*\{[\s\S]*setChecked\(cell, false\);[\s\S]*else if \(isTracked\(cell\)\)\s*\{[\s\S]*setEmpty\(cell\);[\s\S]*else\s*\{[\s\S]*setChecked\(cell, true\);/);
  assert.match(js, /emptyDays:\s*cells\.filter\(isEmpty\)\.map\(getDay\)/);
  assert.match(js, /emptyDays:\s*goal\.emptyDays/);
  assert.match(js, /function updateChart\(\)/);
  assert.match(js, /function getDayScore\(day\)/);
  assert.match(js, /function renderChartShell\(\)/);
  assert.match(js, /endGameMissionCard:\s*endGameCards\.getLegacyMissionState\(\)/);
  assert.match(js, /endGameCards:\s*endGameCards\.getState\(\)/);
  assert.match(js, /endGameCards\.render\(storedState\.endGameCards\)/);
  assert.match(js, /endGameCards\.needsMigration\(parsed\.endGameCards\)/);
  assert.match(endGameCardsJs, /const CARD_CATALOG = \[/);
  assert.match(endGameCardsJs, /normalized\.__order = normalizeOrder\(value\?\.__order\)/);
  assert.match(endGameCardsJs, /__order:\s*\[\.\.\.state\.__order\]/);
  assert.match(endGameCardsJs, /onOrderChange\(visibleOrder\)/);
  assert.match(endGameCardsJs, /\{ id: 'eigen-automaat-rijden', title: 'Eigen automaat rijden' \}/);
  assert.doesNotMatch(endGameCardsJs, /standaloneImage|function createCard\(card, state, index\)/);
  assert.match(endGameCardsJs, /live-momentum-endgame-cards\/\$\{card\.id\}\.png\?v=20260717c/);
  assert.doesNotMatch(endGameCardsJs, /atlasIndex|endgame-goals-atlas/);
  assert.match(endGameCardsJs, /title:\s*'PRP Behandeling'/);
  assert.match(endGameCardsJs, /title:\s*'Ketting & Armband'/);
  assert.match(endGameCardsJs, /title:\s*'Haartransplantatie'/);
  assert.match(endGameCardsJs, /title:\s*'<13% bodyfat'/);
  assert.match(endGameCardsJs, /title:\s*'\+5KG Spiermassa'/);
  assert.match(endGameCardsJs, /title:\s*"Servé's gezondheidsdossier"/);
  assert.match(endGameCardsJs, /title:\s*'Ruben’s Trading System'/);
  assert.match(endGameCardsJs, /title:\s*'Gewenste kledingkast'/);
  assert.match(endGameCardsJs, /\{ id: '2030', title: '2030\.\.\.', type: 'destination' \}/);
  assert.match(endGameCardsJs, /\{ id: 'oktober-2024', title: 'Oktober 2024…', type: 'origin' \}/);
  assert.match(endGameCardsJs, /return \[ORIGIN_CARD_ID, \.\.\.requestedOrder, \.\.\.remainingOrder, DESTINATION_CARD_ID\]/);
  assert.match(endGameCardsJs, /dataset\.endGameCardFixed = 'true'/);
  assert.match(endGameCardsJs, /card\.type === 'destination' \? 'EINDPUNT' : 'END GAME'/);
  assert.match(endGameCardsJs, /card\.type === 'origin' \? 'HIER BEGON HET' : 'WIE BEN IK DAN\?'/);
  assert.match(endGameCardsJs, /if \(!isFixed\) article\.append\(createCompletionOverlay\(\), createActions\(card, state\.completed\)\)/);
  assert.match(endGameCardsJs, /getLegacyMissionState: \(\) => \(\{ \.\.\.state\[LEGACY_MISSION_ID\] \}\)/);
  [
    'Tanden rechtzetten', 'Black Gel voorraad', 'Tandenbleek voorraad', 'Gezichtsbeharing naar wens',
    'Bestaanszekerheid bedrijf', 'Eigen koophuis kopen', 'Leuke vriendin', 'Eigen Cinema',
    'Eigen kantoor', 'Kantoorpand in Haaren', 'Nieuwe Whoop', 'Gezondheidscenter',
    "Servé's gezondheidsdossier", 'Ruben zet toto', 'world watcher', 'Transfermarkt',
    'Ruben’s Company', 'Ruben’s Trading System', 'Gewenst lang kapsel', 'Gewenste kledingkast', '2030...', 'Oktober 2024…'
  ].forEach((title) => assert.equal(endGameCardsJs.includes(title), true, `missing card title: ${title}`));
  assert.match(endGameCardsJs, /dataset\.endGameCardAction = 'toggle-complete'/);
  assert.match(endGameCardsJs, /dataset\.endGameCardAction = 'remove'/);
  assert.match(endGameCardsJs, /Nogmaals: verwijderen/);
  assert.match(endGameCardsJs, /updateCard\(cardId, \{ deleted: true \}\)/);
  assert.match(endGameCardsJs, /onStateChange\(\);/);
  assert.match(endGameCardsJs, /window\.SoftoraMomentumEndGameCards/);
  assert.match(endGameInteractionsJs, /const DRAG_THRESHOLD = 8/);
  assert.match(endGameInteractionsJs, /const MAX_WHEEL_STEP = 48/);
  assert.match(endGameInteractionsJs, /addEventListener\('pointerdown'/);
  assert.match(endGameInteractionsJs, /card\.dataset\.endGameCardFixed === 'true'/);
  assert.match(endGameInteractionsJs, /addEventListener\('pointermove'/);
  assert.match(endGameInteractionsJs, /addEventListener\('pointerup', finishDrag\)/);
  assert.match(endGameInteractionsJs, /onOrderChange\(getVisibleCardIds\(\)\)/);
  assert.match(endGameInteractionsJs, /event\.preventDefault\(\);[\s\S]*wheelTarget = nextTarget/);
  assert.match(endGameInteractionsJs, /clamp\(distance \* WHEEL_EASING, -MAX_WHEEL_STEP, MAX_WHEEL_STEP\)/);
  assert.match(endGameInteractionsJs, /addEventListener\('pointerdown', cancelWheelScroll\)/);
  assert.match(endGameInteractionsJs, /\{ passive: false \}/);
  assert.match(endGameInteractionsJs, /window\.SoftoraMomentumEndGameInteractions/);
  assert.match(videoJs, /const VIDEO_ID = 'XwtdR-oW6XA'/);
  assert.match(videoJs, /youtube-nocookie\.com\/embed\/\$\{VIDEO_ID\}/);
  assert.match(videoJs, /controls:\s*'0'/);
  assert.match(videoJs, /enablejsapi:\s*'1'/);
  assert.match(videoJs, /cc_load_policy:\s*'0'/);
  assert.match(videoJs, /interactionLayer\.className = 'momentum-video-interaction'/);
  assert.match(videoJs, /sendPlayerCommand\(shouldPause \? 'pauseVideo' : 'playVideo'\)/);
  assert.match(videoCss, /\.momentum-video-stage iframe\s*\{[\s\S]*top:\s*-23%;[\s\S]*left:\s*0;[\s\S]*width:\s*100%;[\s\S]*height:\s*146%;[\s\S]*pointer-events:\s*none;/);
  assert.match(videoCss, /\.momentum-video-interaction\s*\{[\s\S]*position:\s*absolute;[\s\S]*inset:\s*0;[\s\S]*background:\s*transparent;/);
  assert.match(videoJs, /autoplay:\s*'1'/);
  assert.match(videoJs, /mute:\s*'0'/);
  assert.match(videoJs, /iframe\.allow = 'autoplay; encrypted-media'/);
  assert.match(videoJs, /dialog\.showModal\(\)/);
  assert.match(videoJs, /player\.replaceChildren\(\)/);
  assert.match(videoJs, /dialog\.addEventListener\('close'/);
  assert.doesNotMatch(js, /renderLineChart|setChartMode|chartMode|chartSwitches|getVisibleScore/);
  assert.match(js, /function renderGridShell\(goals\)/);
  assert.match(js, /function createGoalDragHandle\(goal\)/);
  assert.match(js, /function removeGoal\(goalId\)/);
  assert.match(js, /goalActions\.create\(goal\)/);
  assert.match(js, /goalActions\.isClickSuppressed\(\)/);
  assert.match(js, /window\.addEventListener\('scroll', \(\) => goalActions\.close\(\), true\)/);
  assert.match(goalActionsJs, /const DRAG_THRESHOLD_PX = 6;/);
  assert.match(goalActionsJs, /distance >= DRAG_THRESHOLD_PX/);
  assert.match(goalActionsJs, /Date\.now\(\) < suppressClickUntil/);
  assert.match(goalActionsJs, /handle\.getBoundingClientRect\(\)/);
  assert.match(goalActionsJs, /window\.SoftoraMomentumGoalActions = \{ createController \}/);
  assert.match(js, /data-goal-action/);
  assert.match(js, /Nogmaals: verwijderen/);
  assert.match(js, /function reorderGoal\(goalId, targetGoalId\)/);
  assert.match(js, /function moveGoalByOffset\(goalId, offset\)/);
  assert.match(js, /grid\.addEventListener\('dragstart'/);
  assert.match(js, /grid\.addEventListener\('dragover'/);
  assert.match(js, /grid\.addEventListener\('drop'/);
  assert.match(js, /grid\.addEventListener\('dragend'/);
  assert.match(js, /event\.key === 'ArrowUp'/);
  assert.match(js, /renderReorderedGoals\(goals\);/);
  assert.match(js, /function createGoalRow\(\)/);
  assert.match(js, /function removeLegacyTrailingGoalPlaceholders\(goals\)/);
  assert.match(js, /needsMigration/);
  assert.match(js, /rowHeader\.dataset\.goalDraft = 'true'/);
  assert.match(js, /goals\.push\(\{ \.\.\.draftGoal, label: '', isDraft: true \}\)/);
  assert.match(js, /delete row\.dataset\.goalDraft/);
  assert.match(js, /if \(!storedState \|\| storedState\.needsMigration\)/);
  assert.match(js, /label\.dataset\.placeholder = 'Vul je doel in'/);
  assert.match(js, /function refreshCellData\(\)/);
  assert.match(js, /function updateTodayColumnEnd/);
  assert.match(js, /closest\('\.add-goal'\)/);
  assert.match(js, /addButton\.textContent = '\+'/);
  assert.match(js, /rowHeader\.append\(addButton\);[\s\S]*className = 'goal-icon-button'/);
  assert.match(js, /rowHeader\.append\(iconButton, createLabel\(goal\.label, goal\.isDraft\), dragHandle, goalActions\.create\(goal\)\)/);
  assert.match(js, /createGoalHeader\(goal, index === goals\.length - 1\)/);
  assert.match(js, /function openIconPicker\(trigger\)/);
  assert.match(js, /function renderIconPickerResults\(searchValue = ''\)/);
  assert.match(js, /event\.key === 'Escape'/);
  assert.match(js, /event\.target === backdrop/);
  assert.match(js, /className = 'goal-icon-button'/);
  assert.match(js, /iconKey:\s*goal\.iconKey/);
  assert.match(js, /row\.dataset\.iconKey = icon\.key/);
  assert.match(js, /markStateChanged\(\);[\s\S]*closeIconPicker\(\);/);
  assert.doesNotMatch(js, /habit-add-cell|habit-add/);
  assert.match(js, /is-untracked/);
  assert.match(js, /day >= TODAY/);
  assert.match(js, /is-missed/);
  assert.match(js, /is-warning/);
  assert.match(js, /is-danger/);
  assert.match(js, /aria-checked/);
  assert.doesNotMatch(js, /scorePoints|100 \/ 100/);
  assert.doesNotMatch(js, /scoreValue|todayScore|Score vandaag/);
  assert.match(js, /STATE_SCOPE = 'premium_live_momentum'/);
  assert.match(js, /calendar\.getMonthStateKey\(PERIOD_KEY\)/);
  assert.match(js, /window\.SoftoraUiStateClient/);
  assert.match(js, /uiStateClient\.get\(STATE_SCOPE\)/);
  assert.match(js, /uiStateClient\.set\(STATE_SCOPE/);
  assert.match(js, /patch:\s*\{ \[STATE_KEY\]: JSON\.stringify\(snapshot\) \}/);
  assert.doesNotMatch(js, /replace:\s*true/);
  assert.match(js, /calendar\.findLatestPriorMonthStateKey\(values, PERIOD_KEY\)/);
  assert.match(js, /values\[calendar\.LEGACY_STATE_KEY\]/);
  assert.match(js, /function parseCarriedState\(rawValue\)/);
  assert.match(js, /parsed\.version !== STATE_VERSION/);
  assert.match(js, /window\.location\.reload\(\)/);
  assert.match(js, /response\.source !== 'supabase'/);
  assert.match(js, /function parseStoredState\(rawValue, options = \{\}\)/);
  assert.match(js, /function scheduleStateWrite\(options = \{\}\)/);
  assert.match(js, /function markStateChanged\(\)/);
  assert.match(js, /function flushStateWrite\(\)/);
  assert.match(js, /label\.addEventListener\('input',[\s\S]*markStateChanged\(\)/);
  assert.match(js, /window\.addEventListener\('pagehide', flushStateWrite\)/);
  assert.match(js, /queuedKeepalive = true/);
  assert.match(js, /MAX_SAVE_RETRIES = 3/);
  assert.doesNotMatch(js, /is-soft/);
  assert.doesNotMatch(js, /localStorage|sessionStorage/);
});

test('live momentum Supabase-scope is alleen voor Full Acces accounts', () => {
  const scopeConfig = read('server/config/admin-ui-state-scopes.js');

  assert.match(scopeConfig, /'premium_live_momentum'/);
  assert.match(scopeConfig, /ADMIN_ONLY_UI_STATE_SCOPES/);
});
