const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const repoRoot = path.resolve(__dirname, '../..');

function read(fileName) {
  return fs.readFileSync(path.join(repoRoot, fileName), 'utf8');
}

test('live momentum page renders the requested dashboard surface', () => {
  const html = read('live-momentum.html');

  assert.match(html, /<title>ATTACK, ATTACK, ATTACK\. \| Softora<\/title>/);
  assert.match(html, /href="\/assets\/fonts\.css\?v=20260409a"/);
  assert.match(html, /href="\/assets\/personnel-theme\.css\?v=20260519b"/);
  assert.match(html, /href="\/assets\/premium-sidebar-autopilot\.css\?v=20260611a"/);
  assert.match(html, /href="\/assets\/live-momentum\.css\?v=20260716i"/);
  assert.match(html, /<script src="\/assets\/personnel-theme\.js\?v=20260715a" defer><\/script>/);
  assert.match(html, /<script src="\/assets\/premium-sidebar-autopilot\.js\?v=20260611a" defer><\/script>/);
  assert.match(html, /<script src="\/assets\/premium-ui-state-client\.js\?v=20260605a"><\/script>/);
  assert.match(html, /<script src="\/assets\/live-momentum-icon-catalog\.js\?v=20260716b" defer><\/script>/);
  assert.match(html, /<script src="\/assets\/live-momentum\.js\?v=20260716d" defer><\/script>/);
  assert.match(html, /<div class="dashboard-layout momentum-layout" data-sidebar-shell="canonical">/);
  assert.match(html, /<aside class="sidebar" data-sidebar-ready="true" data-static-sidebar="1" aria-label="Premium navigatie">/);
  assert.match(html, /data-sidebar-key="dashboard"/);
  assert.match(html, /data-sidebar-key="settings"/);
  assert.match(html, /assets\/premium-sidebar-profile-prefill\.js\?v=20260715a/);
  assert.doesNotMatch(html, /data-live-momentum-sidebar-host/);
  assert.match(html, /<main class="main-content momentum-page" aria-labelledby="momentum-title">/);
  assert.match(html, /<h1 id="momentum-title">ATTACK, ATTACK, ATTACK\.<\/h1>/);
  assert.match(html, /Juli 2026 .* gestart op 13 juli/);
  assert.doesNotMatch(html, /today-score|score-label|Score vandaag/);
  assert.doesNotMatch(html, /score-points|100 \/ 100|punten<\/span>/);
  assert.match(html, /<div class="bar-chart" aria-hidden="true"><\/div>/);
  assert.doesNotMatch(html, /chart-switch|data-chart-mode|Grafiekweergave/);
  assert.match(html, /<div class="habit-grid" role="table" aria-label="Momentum taken in juli"><\/div>/);
  assert.match(html, /<\/section>\s*<h2 class="end-game-title">END GAME<\/h2>\s*<div class="momentum-art-quotes" aria-hidden="true">/);
  assert.match(html, /<span class="momentum-art-quote is-end-game">The end game is to win<\/span>/);
  assert.match(html, /<span class="momentum-art-quote is-attack">Attack, attack, attack<\/span>/);
  assert.match(html, /<span class="momentum-art-quote is-sleeping">Sleeping is for losers<\/span>/);
  assert.match(html, /<span class="momentum-art-quote is-winners">In life there are winners and losers<\/span>/);
  assert.match(html, /<span class="momentum-art-quote is-old-days">Nog een rondje voor die oude dagen<\/span>/);
  assert.match(html, /<div class="momentum-watermark" aria-hidden="true">[\s\S]*Never[\s\S]*Ever[\s\S]*Quit[\s\S]*<\/div>/);
  assert.match(html, /13 juli is vandaag/);
  assert.doesNotMatch(html, /laatste 30 dagen/);
  assert.doesNotMatch(html, /Dag<br>/);
  assert.doesNotMatch(html, /chart-legend|legend-dot|Legenda/);
  assert.doesNotMatch(html, /Groen|Oranje|Rood/);
  assert.doesNotMatch(html, /Afgerond/);
  assert.doesNotMatch(html, /Dag 1 toevoegen/);
  assert.doesNotMatch(html, /Discipline vandaag/);
  assert.doesNotMatch(html, /Focus\. Consistentie\. Groei\./);
  assert.doesNotMatch(html, /motivation-strip/);
  assert.doesNotMatch(html, /closing-quote/);
  assert.doesNotMatch(html, /Nog te gaan/);
  assert.doesNotMatch(html, /<script(?![^>]*\bsrc=)[^>]*>/i);
});

test('live momentum stylesheet keeps the visual replica self-contained', () => {
  const css = read('assets/live-momentum.css');

  assert.match(css, /--page-bg:\s*#f8f7f4;/);
  assert.match(css, /--ink:\s*#1a1a2e;/);
  assert.match(css, /--muted:\s*#606272;/);
  assert.match(css, /--muted-soft:\s*#9599a8;/);
  assert.match(css, /--font-sans:\s*"Inter"/);
  assert.match(css, /--font-display:\s*"Oswald"/);
  assert.match(css, /--good:\s*#2ecc71;/);
  assert.match(css, /--warning:\s*#f39c12;/);
  assert.match(css, /--danger:\s*#e74c3c;/);
  assert.match(css, /body\s*\{[\s\S]*background:\s*var\(--page-bg\);/);
  assert.match(css, /body\s*\{[\s\S]*font-family:\s*var\(--font-sans\);/);
  assert.match(css, /\.momentum-page\s*\{[\s\S]*padding:\s*3rem 3rem 1\.8rem;/);
  assert.match(css, /\.momentum-head h1\s*\{[\s\S]*font-family:\s*var\(--font-display\);/);
  assert.match(css, /\.momentum-head h1\s*\{[\s\S]*font-size:\s*2rem;/);
  assert.match(css, /\.momentum-head h1\s*\{[\s\S]*text-transform:\s*uppercase;/);
  const letterSpacingValues = Array.from(css.matchAll(/letter-spacing:\s*([^;]+);/g), (match) => match[1].trim());
  assert.ok(letterSpacingValues.length > 0);
  assert.deepEqual([...new Set(letterSpacingValues)], ['0']);
  assert.doesNotMatch(css, /purple/i);
  assert.doesNotMatch(css, /88366b|74265c|91436f|7f426b/i);
  assert.match(css, /\.bar-chart\s*\{[\s\S]*grid-template-columns:\s*repeat\(var\(--day-count, 31\),/);
  assert.doesNotMatch(css, /chart-switch|is-line-mode|\.line-(?:stage|grid|segment|point|day-axis)/);
  assert.match(css, /\.habit-grid\s*\{[\s\S]*grid-template-columns:\s*minmax\(190px, 12vw\) repeat\(var\(--day-count, 31\), minmax\(32px, 1fr\)\);/);
  assert.match(css, /width:\s*100%;/);
  assert.doesNotMatch(css, /width:\s*min\(1320px, 100%\);/);
  assert.doesNotMatch(css, /\.momentum-hero,\s*\.habit-board,\s*\.closing-quote/);
  assert.doesNotMatch(css, /\.chart-card\s*\{[^}]*border-top:/);
  assert.doesNotMatch(css, /\.chart-card\s*\{[^}]*border-bottom:/);
  assert.match(css, /\.habit-board\s*\{[^}]*overflow-x:\s*auto;[^}]*scrollbar-width:\s*none;/);
  assert.match(css, /\.habit-board::\-webkit-scrollbar\s*\{[^}]*display:\s*none;/);
  assert.match(css, /\.end-game-title\s*\{[\s\S]*margin:\s*clamp\(3\.5rem, 7vh, 6rem\) auto 0;[\s\S]*font-family:\s*var\(--font-display\);[\s\S]*font-size:\s*2rem;[\s\S]*text-align:\s*center;/);
  assert.match(css, /\.momentum-art-quotes\s*\{[\s\S]*grid-template-columns:\s*minmax\(0, 1fr\) minmax\(0, 1\.12fr\);[\s\S]*pointer-events:\s*none;/);
  assert.match(css, /\.momentum-art-quote\s*\{[\s\S]*color:\s*transparent;[\s\S]*font-family:\s*var\(--font-display\);[\s\S]*\-webkit-text-stroke:\s*1px rgba\(26, 26, 46, \.07\);/);
  assert.match(css, /\.momentum-art-quote\.is-sleeping\s*\{[\s\S]*grid-column:\s*1 \/ -1;[\s\S]*text-align:\s*center;/);
  assert.match(css, /\.momentum-watermark\s*\{[\s\S]*pointer-events:\s*none;/);
  assert.match(css, /\.momentum-watermark\s*\{[\s\S]*\-webkit-text-stroke:\s*1px rgba\(26, 26, 46, \.075\);/);
  assert.match(css, /\.momentum-watermark span:last-child\s*\{[\s\S]*rgba\(35, 159, 88, \.045\)/);
  assert.doesNotMatch(css, /\.chart-legend|\.legend-dot/);
  assert.match(css, /\.bar\.is-warning\s*\{[\s\S]*var\(--warning\)/);
  assert.match(css, /\.bar\.is-danger\s*\{[\s\S]*var\(--danger\)/);
  assert.match(css, /\.status\.is-today-end\s*\{[\s\S]*border-bottom:\s*2px solid var\(--good-line\);/);
  assert.match(css, /\.status\.is-untracked::before\s*\{[\s\S]*background:\s*#d4d9df;/);
  assert.match(css, /\.status\.is-missed::before\s*\{[\s\S]*background-color:\s*var\(--danger\);/);
  assert.doesNotMatch(css, /\.status\.is-soft|is-soft::before/);
  assert.match(css, /\.habit-label:focus\s*\{[\s\S]*box-shadow:\s*0 0 0 2px rgba\(86, 196, 134, \.34\);/);
  assert.match(css, /\.add-goal\s*\{[\s\S]*border:\s*0;/);
  assert.match(css, /\.add-goal\s*\{[\s\S]*border-radius:\s*0;/);
  assert.match(css, /\.add-goal\s*\{[\s\S]*background:\s*transparent;/);
  assert.match(css, /\.goal-icon-button\s*\{[\s\S]*cursor:\s*pointer;/);
  assert.match(css, /\.icon-picker-search\s*\{[\s\S]*width:\s*100%;/);
  assert.match(css, /\.icon-picker-results\s*\{[\s\S]*grid-template-columns:/);
  assert.match(css, /\.icon-picker-categories\s*\{[\s\S]*overflow-x:\s*auto;/);
  assert.match(css, /\.icon-picker-category\[aria-pressed="true"\]/);
  assert.match(css, /\.icon-picker-backdrop\[hidden\]\s*\{[\s\S]*display:\s*none;/);
  assert.doesNotMatch(css, /\.habit-add(?:-cell)?\s*\{/);
  assert.doesNotMatch(css, /\.score-points\s*\{/);
  assert.doesNotMatch(css, /\.today-score|\.score-label/);
  assert.doesNotMatch(css, /\.habit-name-empty/);
  assert.match(css, /\.habit-spacer\s*\{[\s\S]*font-family:\s*var\(--font-display\);/);
  assert.match(css, /\.habit-spacer\s*\{[\s\S]*font-weight:\s*500;/);
  assert.doesNotMatch(css, /\.motivation-strip/);
  assert.doesNotMatch(css, /\.quote-card/);
  assert.doesNotMatch(css, /\.closing-quote/);
  assert.match(css, /\.status:focus-visible::before\s*\{[\s\S]*box-shadow:\s*0 0 0 3px rgba\(86, 196, 134, \.3\);/);
  assert.match(css, /@media \(max-width:\s*780px\)/);
});

test('live momentum script wires habit toggles to chart and persisted state', () => {
  const js = read('assets/live-momentum.js');

  assert.match(js, /startDay:\s*13/);
  assert.match(js, /today:\s*13/);
  assert.match(js, /lastDay:\s*31/);
  assert.match(js, /const TOTAL_DAYS = DAYS\.length;/);
  assert.match(js, /Juli 2026|shortLabel:\s*'Jul'/);
  assert.match(js, /DEFAULT_GOALS/);
  assert.match(js, /window\.SoftoraMomentumIconCatalog/);
  assert.match(js, /ICON_CATEGORIES/);
  assert.match(js, /function renderIconPickerCategories\(\)/);
  assert.match(js, /Zoek op icoon of betekenis/);
  assert.match(js, /Workout/);
  assert.match(js, /90 min deep work/);
  assert.match(js, /Dagdoel behalen/);
  assert.match(js, /Gezonde voeding/);
  assert.match(js, /function getScoreBand\(score\)/);
  assert.match(js, /function toggleCell\(cell\)/);
  assert.match(js, /function updateChart\(\)/);
  assert.match(js, /function getDayScore\(day\)/);
  assert.match(js, /function renderChartShell\(\)/);
  assert.doesNotMatch(js, /renderLineChart|setChartMode|chartMode|chartSwitches|getVisibleScore/);
  assert.match(js, /function renderGridShell\(goals\)/);
  assert.match(js, /function createGoalRow\(\)/);
  assert.match(js, /function refreshCellData\(\)/);
  assert.match(js, /function updateTodayColumnEnd/);
  assert.match(js, /closest\('\.add-goal'\)/);
  assert.match(js, /addButton\.textContent = '\+'/);
  assert.match(js, /createGoalHeader\(goal, index === goals\.length - 1\)/);
  assert.match(js, /function openIconPicker\(trigger\)/);
  assert.match(js, /function renderIconPickerResults\(searchValue = ''\)/);
  assert.match(js, /event\.key === 'Escape'/);
  assert.match(js, /event\.target === backdrop/);
  assert.match(js, /className = 'goal-icon-button'/);
  assert.match(js, /iconKey:\s*goal\.iconKey/);
  assert.match(js, /row\.dataset\.iconKey = icon\.key/);
  assert.match(js, /markStateChanged\(\);[\s\S]*closeIconPicker\(\);/);
  assert.doesNotMatch(js, /habit-add-cell|habit-add/);
  assert.match(js, /is-untracked/);
  assert.match(js, /day >= TODAY/);
  assert.match(js, /is-missed/);
  assert.match(js, /is-warning/);
  assert.match(js, /is-danger/);
  assert.match(js, /aria-checked/);
  assert.doesNotMatch(js, /scorePoints|100 \/ 100/);
  assert.doesNotMatch(js, /scoreValue|todayScore|Score vandaag/);
  assert.match(js, /STATE_SCOPE = 'premium_live_momentum'/);
  assert.match(js, /STATE_KEY = 'softora_live_momentum_state_v1'/);
  assert.match(js, /window\.SoftoraUiStateClient/);
  assert.match(js, /uiStateClient\.get\(STATE_SCOPE\)/);
  assert.match(js, /uiStateClient\.set\(STATE_SCOPE/);
  assert.match(js, /replace:\s*true/);
  assert.match(js, /response\.source !== 'supabase'/);
  assert.match(js, /function parseStoredState\(rawValue\)/);
  assert.match(js, /function scheduleStateWrite\(options = \{\}\)/);
  assert.match(js, /function markStateChanged\(\)/);
  assert.match(js, /function flushStateWrite\(\)/);
  assert.match(js, /label\.addEventListener\('input',[\s\S]*markStateChanged\(\)/);
  assert.match(js, /window\.addEventListener\('pagehide', flushStateWrite\)/);
  assert.match(js, /queuedKeepalive = true/);
  assert.match(js, /MAX_SAVE_RETRIES = 3/);
  assert.doesNotMatch(js, /is-soft/);
  assert.doesNotMatch(js, /localStorage|sessionStorage/);
});

test('live momentum Supabase-scope is alleen voor Full Acces accounts', () => {
  const scopeConfig = read('server/config/admin-ui-state-scopes.js');

  assert.match(scopeConfig, /'premium_live_momentum'/);
  assert.match(scopeConfig, /ADMIN_ONLY_UI_STATE_SCOPES/);
});
