const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');

test('premium seo NL UI: tabs, paginas, blogcampagne', () => {
  const filePath = path.join(__dirname, '../../premium-seo.html');
  const dashboardPath = path.join(__dirname, '../../assets/seo-dashboard.js');
  const source = fs.readFileSync(filePath, 'utf8');
  const dashboardSource = fs.readFileSync(dashboardPath, 'utf8');

  assert.match(source, /<button class="tab active" type="button" data-seo-tab="scan">SEO Scan<\/button>/);
  assert.match(source, /<button class="tab" type="button" data-seo-tab="paginas">Pagina's<\/button>/);
  assert.match(source, /<button class="tab" type="button" data-seo-tab="blogs">Blogs<\/button>/);
  assert.match(source, /<button class="tab" type="button" data-seo-tab="analytics">Google Analytics<\/button>/);
  assert.match(source, /id="scan-btn" type="button" data-seo-action="scan"/);
  assert.match(source, /id="blog-activate-btn" data-seo-action="activate-blog-campaign"/);
  assert.match(source, /id="blog-pause-btn" data-seo-action="pause-blog-campaign"/);
  assert.match(source, /data-seo-action="close-goal-modal"/);
  assert.match(source, /data-seo-action="confirm-goal-modal"/);
  assert.match(source, /data-seo-action="optimise-page" data-seo-page-slug="\$\{s\}"/);
  assert.match(source, /data-seo-char-count="\$\{s\}-meta-title-count" data-seo-char-max="60"/);
  assert.match(source, /data-seo-char-count="\$\{s\}-meta-desc-count" data-seo-char-max="160"/);
  assert.match(source, /data-seo-char-count="\$\{s\}-og-desc-count" data-seo-char-max="200"/);
  assert.match(source, /data-seo-lock-input/);
  assert.match(source, /data-seo-lock-submit/);
  assert.match(source, /function bindSeoStaticActions\(\)/);
  assert.match(source, /button\.addEventListener\('click', \(\) => \{[\s\S]*switchTab\(button\.dataset\.seoTab \|\| 'scan', button\);/);
  assert.match(source, /'optimise-page': \(_event, button\) => \{[\s\S]*optimisePage\(button\.dataset\.seoPageSlug, button\);/);
  assert.match(source, /button\.addEventListener\('click', \(event\) => handler\(event, button\)\)/);
  assert.match(source, /input\.addEventListener\('input', \(\) => \{[\s\S]*charCount\(input\.id, countId, max\);/);
  assert.match(source, /lockSubmit\.addEventListener\('click', unlockSeoContentArea\)/);
  assert.doesNotMatch(source, /onclick="switchTab\(/);
  assert.doesNotMatch(source, /onclick="startScan\(/);
  assert.doesNotMatch(source, /onclick="activateBlogCampaign\(/);
  assert.doesNotMatch(source, /onclick="pauseBlogCampaignDemo\(/);
  assert.doesNotMatch(source, /onclick="closeSeoGoalModal\(/);
  assert.doesNotMatch(source, /onclick="confirmSeoGoalAndOptimise\(/);
  assert.doesNotMatch(source, /onclick="optimisePage\(/);
  assert.doesNotMatch(source, /oninput="charCount\(/);
  assert.doesNotMatch(source, /onkeydown="if\(event\.key==='Enter'\)unlockSeoContentArea\(\)"/);
  assert.doesNotMatch(source, /tab-productpaginas/);
  assert.match(source, /<div class="tab-panel" id="tab-analytics">/);
  assert.doesNotMatch(source, /id="tab-keywords"/);
  assert.doesNotMatch(source, /switchTab\('keywords'/);
  assert.match(source, /<div class="tab-panel" id="tab-paginas">/);
  assert.match(source, /id="seo-pages-root"/);
  assert.match(source, /id="home-meta-title"/);
  assert.doesNotMatch(source, /id="btn-all"/);
  assert.doesNotMatch(source, /function optimiseAllPages/);
  assert.match(source, /function optimisePage\(/);
  assert.match(source, /function runOptimisePage\(/);
  assert.match(source, /id="seo-goal-modal"/);
  assert.match(source, /minimaal 10 tekens/i);
  assert.match(source, /Pagina optimaliseren/);
  assert.match(source, /<div class="tab-panel" id="tab-blogs">/);
  assert.match(source, /id="blog-campaign-wrap"/);
  assert.match(source, /id="blog-word-count"/);
  assert.match(source, /Campagne online zetten/);
  assert.match(source, /activateBlogCampaign\(\)/);
  assert.doesNotMatch(dashboardSource, /\.innerHTML\s*=/);
  assert.match(dashboardSource, /target\.replaceChildren\(\);/);
  assert.match(dashboardSource, /elements\.auditList\.replaceChildren\(\);/);
});
