const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');

const { createKnownPrettyPageSlugToFile } = require('../../server/config/page-routing');

test('sportschool logboek page is available as installable pretty page', () => {
  const pagePath = path.join(__dirname, '../../sportschool.html');
  const pageSource = fs.readFileSync(pagePath, 'utf8');
  const stylesSource = fs.readFileSync(path.join(__dirname, '../../assets/sportschool-logboek.css'), 'utf8');
  const scriptSource = fs.readFileSync(path.join(__dirname, '../../assets/sportschool-logboek.js'), 'utf8');
  const prettyPages = createKnownPrettyPageSlugToFile(new Set(['sportschool.html']));

  assert.equal(prettyPages.get('sportschool'), 'sportschool.html');
  assert.match(pageSource, /<title>Servé's Logboek<\/title>/);
  assert.match(pageSource, /apple-mobile-web-app-capable/);
  assert.match(pageSource, /apple-mobile-web-app-title" content="Servé's logboek"/);
  assert.match(pageSource, /noindex,nofollow/);
  assert.match(pageSource, /assets\/sportschool-logboek\.css/);
  assert.match(pageSource, /assets\/premium-ui-state-client\.js/);
  assert.match(pageSource, /assets\/sportschool-supabase-config\.js/);
  assert.match(pageSource, /assets\/sportschool-logboek\.js/);
  assert.match(pageSource, /data-day-trigger/);
  assert.match(pageSource, /data-add-exercise/);
  assert.match(pageSource, /data-exercise-list/);
  assert.doesNotMatch(pageSource, /<script>[\s\S]*<\/script>/i);
  assert.match(stylesSource, /font-family: Oswald/);
  assert.match(stylesSource, /\.delete-action/);
  assert.match(stylesSource, /\.day-picker-backdrop/);
  assert.match(scriptSource, /sportschool_logboek/);
  assert.match(scriptSource, /softora_sportschool_logbook/);
  assert.match(scriptSource, /SoftoraSportschoolSupabase/);
  assert.match(scriptSource, /SoftoraUiStateClient/);
  assert.match(scriptSource, /scheduleRemoteSave/);
  assert.match(scriptSource, /persistRemoteSave/);
  assert.match(scriptSource, /keepalive: options\.keepalive === true/);
  assert.match(scriptSource, /pagehide/);
  assert.match(scriptSource, /visibilitychange/);
  assert.match(scriptSource, /lastRemoteSnapshotJson = snapshotJson/);
  assert.match(scriptSource, /createDefaultState/);
  assert.match(scriptSource, /async function boot/);
  assert.match(scriptSource, /await loadRemoteState\(\)/);
  assert.doesNotMatch(scriptSource, /render\(\);\s*loadRemoteState\(\);/);
  assert.match(scriptSource, /dayChoiceTitle/);
  assert.match(scriptSource, /day\.id === currentWeekday\(\) \? 'Vandaag' : day\.title/);
  assert.doesNotMatch(scriptSource, /\{\s*id:\s*'today'/);
  assert.match(scriptSource, /Bankdrukken/);
  assert.match(scriptSource, /Schuine dumbbell press/);
  assert.match(scriptSource, /Seated row/);
  assert.match(scriptSource, /Lat pulldown/);
  assert.match(scriptSource, /DEFAULT_EXERCISES\.slice\(0, 4\)/);
  assert.doesNotMatch(scriptSource, /localStorage/);
  assert.match(scriptSource, /setPointerCapture/);
  assert.match(scriptSource, /pointerdown/);
  assert.match(scriptSource, /Verwijder/);
  assert.match(scriptSource, /IS EEN RUSTDAG/);
  assert.match(stylesSource, /\.exercise-card\s*\{[\s\S]*?padding: 11px 12px;/);
  assert.match(stylesSource, /\.exercise-list\s*\{[\s\S]*?gap: 8px;/);
  assert.match(stylesSource, /\.metric\s*\{[\s\S]*?width: 34px;/);
  assert.match(stylesSource, /\.exercise-title\s*\{[\s\S]*?font-size: 14px;/);
  assert.match(stylesSource, /\.exercise-notes\s*\{[\s\S]*?font-size: 12px;/);
  assert.match(stylesSource, /:focus-within/);
  assert.doesNotMatch(stylesSource, /\.day-trigger::after/);
});
