const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '../..');
test('voicesoftware route and toekomst entry serve the complete public page', () => {
  const config = JSON.parse(fs.readFileSync(path.join(root, 'vercel.json'), 'utf8'));
  assert.ok(config.rewrites.some(r => r.source === '/voicesoftware' && r.destination === '/assets/voicesoftware/index.html'));
  const entry = fs.readFileSync(path.join(root, 'assets/entry/toekomst.html'), 'utf8');
  assert.match(entry, /href="\/voicesoftware"/);
  const html = fs.readFileSync(path.join(root, 'assets/voicesoftware/index.html'), 'utf8');
  assert.match(html, /AI-TELEFONIST VAN SOFTORA/);
  assert.match(html, /De telefoon gaat\.<br>Jij werkt<br>/);
  assert.doesNotMatch(html, /noindex|localhost|127\.0\.0\.1|Lokale demo/);
  for (const match of html.matchAll(/(?:src|href)="(\/assets\/[^"?]+)/g)) assert.ok(fs.existsSync(path.join(root, match[1])), match[1]);
  assert.match(html, /src="\/assets\/service-landing\/professional-services\.js"/);
  assert.equal([...html.matchAll(/data-voice aria-pressed="false"/g)].length, 3);
  assert.match(html, /stem van je browser/);
  const script = fs.readFileSync(path.join(root, 'assets/service-landing/professional-services.js'), 'utf8');
  assert.match(script, /speechSynthesis/);
  assert.match(script, /Er is geen Nederlandse stem beschikbaar/);
  assert.match(script, /synth\?\.cancel\(\)/);
  assert.match(script, /window\.addEventListener\('pagehide', stop\)/);
  assert.match(script, /document\.addEventListener\('visibilitychange'/);
});
