-- Subscription jobs share the canonical job store. Cron never claims this lane.
create or replace function public.softora_webdesign_subscription_claim(p_claim text)
returns jsonb language plpgsql security invoker set search_path = '' as $$
declare j public.softora_webdesign_jobs;
begin
  if p_claim !~ '^[a-f0-9-]{36}$' then raise exception 'invalid claim'; end if;
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('webdesign-subscription:' || p_claim, 0));
  select * into j from public.softora_webdesign_jobs where status = 'running'
    and payload->>'executionProvider' = 'codex-subscription' and payload->>'subscriptionClaim' = p_claim;
  if found then return jsonb_build_object('ok', true, 'job', to_jsonb(j)); end if;
  -- Interrupted subscription work is surfaced, never regenerated by the API.
  update public.softora_webdesign_jobs set status = 'error', finished_at = now(), updated_at = now(),
    error = 'Codex op je Mac is onderbroken. Controleer de afbeelding en start de opdracht opnieuw.'
  where payload->>'executionProvider' = 'codex-subscription' and status = 'running'
    and started_at < now() - interval '30 minutes';
  select * into j from public.softora_webdesign_jobs w
  where w.status = 'queued' and w.payload->>'executionProvider' = 'codex-subscription'
    and w.created_at > now() - interval '6 hours'
    and coalesce(w.payload->>'kind', '') = ''
    and coalesce(w.payload->>'generationAttempted', 'false') <> 'true'
    and not exists (select 1 from public.softora_webdesign_jobs b
      where b.job_id = w.payload->>'batchId' and b.owner_key = w.owner_key
        and (b.status = 'error' or b.payload->'batch'->>'status' = 'cancelled'))
  order by w.created_at for update skip locked limit 1;
  if not found then return jsonb_build_object('ok', true, 'job', null); end if;
  update public.softora_webdesign_jobs set status = 'running', started_at = now(), updated_at = now(),
    payload = payload || jsonb_build_object('generationAttempted', true, 'subscriptionClaim', p_claim)
    where job_id = j.job_id returning * into j;
  return jsonb_build_object('ok', true, 'job', to_jsonb(j));
end $$;

create or replace function public.softora_webdesign_subscription_result(p_job_id text, p_claim text, p_action text, p_error text)
returns jsonb language plpgsql security invoker set search_path = '' as $$
declare j public.softora_webdesign_jobs;
begin
  select * into j from public.softora_webdesign_jobs where job_id = p_job_id for update;
  if not found or j.payload->>'executionProvider' is distinct from 'codex-subscription'
    or j.payload->>'subscriptionClaim' is distinct from p_claim then return jsonb_build_object('ok', false, 'reason', 'stopped'); end if;
  if j.status = 'done' then return jsonb_build_object('ok', true, 'done', true); end if;
  if j.status <> 'running' or coalesce(j.payload->>'cancelled', 'false') = 'true'
    or exists (select 1 from public.softora_webdesign_jobs b where b.job_id = j.payload->>'batchId'
      and b.owner_key = j.owner_key and (b.status = 'error' or b.payload->'batch'->>'status' = 'cancelled'))
    then return jsonb_build_object('ok', false, 'reason', 'stopped'); end if;
  if p_action = 'begin' then
    if j.payload->>'subscriptionSavingUntil' is not null
      and (j.payload->>'subscriptionSavingUntil')::timestamptz > now() then return jsonb_build_object('ok', false, 'reason', 'saving'); end if;
    update public.softora_webdesign_jobs set payload = payload ||
      jsonb_build_object('subscriptionSavingUntil', now() + interval '5 minutes'), updated_at = now()
      where job_id = p_job_id returning * into j;
    return jsonb_build_object('ok', true, 'job', to_jsonb(j));
  end if;
  if p_action not in ('done', 'error') then raise exception 'invalid action'; end if;
  update public.softora_webdesign_jobs set status = case when p_action = 'done' then 'done' else 'error' end,
    error = nullif(left(p_error, 1000), ''), finished_at = now(), updated_at = now(),
    payload = (payload - 'subscriptionSavingUntil') || case when p_action = 'done' then
      jsonb_build_object('generation', jsonb_build_object('model', 'gpt-image-2', 'billingMode', 'subscription',
        'quality', '', 'size', '1024x1536', 'usage', null, 'cost', null)) else '{}'::jsonb end
    where job_id = p_job_id;
  return jsonb_build_object('ok', true, 'done', true);
end $$;
revoke all on function public.softora_webdesign_subscription_claim(text) from public, anon, authenticated;
revoke all on function public.softora_webdesign_subscription_result(text,text,text,text) from public, anon, authenticated;
grant execute on function public.softora_webdesign_subscription_claim(text) to service_role;
grant execute on function public.softora_webdesign_subscription_result(text,text,text,text) to service_role;
